DELEM_MSG = '~'
DELEM_USER_ADD = "+"
DELEM_USER_LOGIN = "*"
DELEM_STATUS = "#"
DELEM_SEND = "@"
STATUS_ERROR = "%sERROR" % DELEM_STATUS
STATUS_SUCCESS = "%sSUCCESS" % DELEM_STATUS
STATUS_USER_EXISTS = "%sUSER_EXISTS" % DELEM_STATUS
STATUS_WRONG_CREDENTIAL = "%sWRONG_CREDENTIAL" % DELEM_STATUS

re_user_password = r"^[a-zA-Z]\w{1,19}:\S{8,15}$"
